export enum Part { A, B, C }

export const parts = {
  [Part.A]: [
    'Sorry I can\'t come,',
    'Please forgive my absence,',
    'This is gonna sound crazy but,',
    'Get this,',
    'I can\'t go because',
    'I know your gonna hate me but,',
    'I was minding my own business and BOOM,',
    'I feel terrible but,',
    'This my sound strange but,',
    'I hate to tell you this but,',
    'I\'m sorry but,',
    'I won\'t be able to make it,',
    'Oh boy, this is going to sound crazy but,',
    'I regretfully cannot attend,',
    'This is going to sound like an excuse but,',
    'Guess what,',
    'I can\'t make it,',
    'I really can\'t believe this but,',
    'I can\'t go because',
    'Oh no,',
    'Oh man,',
    'Guess what,',
    'Apparently,',
    'I\'m sorry but,',
    'I\'m sorry running late but,',
    'You\'re not gonna believe this but,',
    'I\'m sorry I can\'t make it but,',
    'It\'s hard to believe it but,',
    'Oh man, this is crazy,',
    'I apologize, I won\'t be able to make it because',
    'It seems that',
    'I will be there in a bit, but right now',
    'It\'s happened again,',
    'I promise it won\'t happen again but,',
    'Can you believe that'
  ],
  [Part.B]: [
    'my nephew',
    'the ghost of Hitler',
    'the Pope',
    'my dentist',
    'a cop',
    'a homeless dwarf named Leo who broke into my basement',
    'a group of angry vegans',
    'a stripper',
    'my ex',
    'a high school marching band',
    'a seven foot tall dominatrix',
    'Dan Rather',
    'a sad clown',
    'the kid from Air Bud',
    'a professional cricket team',
    'my Tinder date',
    'six zombie cheerleaders',
    'a banana the size of a car',
    'a giant panda',
    'a time traveling monkey',
    'a robot with bad breath',
    'a motorcycle gang of lesbian Trump supporters',
    'the band Kool and the Gang',
    'a meet up consisting entirely of identical twins from the Ukraine',
    'the cast of Friends',
    'David Spade',
    'a group of circus clowns',
    'a family of raccoons',
    'a group of angry nuns',
    'a pack of wild dogs',
    'a cashier from Whole Foods',
    'my doctor',
    'a dog named Timmy',
    'my third grade gym teacher',
    'my step father\'s ex-wife',
    'an alien from Jupiter',
    'a fancy man in a top hat',
    'a group of diseased chickens',
  ],
  [Part.C]: [
    'just shit the bed.',
    'died in front of me.',
    'won\'t stop telling me knock knock jokes.',
    'is giving me a nervous breakdown.',
    'gave me syphilis.',
    'poured lemonade in my gas tank.',
    'stabbed me.',
    'found my box of teeth.',
    'stole my bicycle.',
    'posted my nudes on Instagram.',
    'hacked my phone.',
    'hid my car keys.',
    'threatened to poison my family if I don\'t steal the Declaration of Independence.',
    'is marrying my grandpa, and I have to organize the bachelor party.',
    'went back in time and took my virginity.',
    'got hit by a car and I am their emergency contact.',
    'poisoned my dog.',
    'offered to buy me house if I run away and marry them.',
    'got me tickets to Hamilton.',
    'bake me a meat pie and now I have food poisoning.',
    'will not stop playing with my cat.',
    'made me a sandwich and now I am a sandwich.',
    'stole my wallet and spent all my money on salt water taffy.',
    'will not get out of my bathroom.',
    'locked me out of my house and is having a party.',
    'is trying to sell me a time share.',
    'is building a time machine and needs my help.',
    'tied me up and refuses to let me go.',
    'needs my help burying a body.',
    'asked me to be their wingman at their family reunion.',
    'managed to get arrested for solicitation and I am trying to raise bail for them.'
  ]
}
